# Generated by Django 3.0 on 2023-08-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('num_bus', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('climatizado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=45)),
                ('destino', models.CharField(max_length=45)),
                ('fecha_hora', models.DateTimeField()),
                ('precio', models.FloatField()),
                ('clase', models.CharField(max_length=45)),
                ('cupo', models.CharField(max_length=45)),
                ('fk_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalua.Bus')),
                ('fk_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalua.Ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalua.Usuario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='fk_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalua.Empresa'),
        ),
    ]
